global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mysql'
    static_configs:
      - targets: ['localhost:9104']

  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
